### ISSUE TITLE
Question compiling with Homebrew GCC 10.2.0_4

### ISSUE THREAD

**Issue by bolton-lab** [freeseek/mocha#11]
Hey Giulio, have you even seen this gcc compile issue before?
```
plugins/mocha.c:718:36: error: function definition is not allowed here
    double f(double x, void *data) { return -baf_phase_lod(baf, gt_phase, n, imap, path, err_log_prb, baf_sd, x); }
                                   ^
plugins/mocha.c:719:31: error: use of undeclared identifier 'f'
    double x, fx = kmin_brent(f, 0.1, 0.2, NULL, KMIN_EPS, &x);
```

**Comment by freeseek** [comment]
This is weird as gcc supports [nested functions](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html). My guess it that, as explained in [this](https://stackoverflow.com/questions/47921800/there-is-an-error-when-compiling-a-c-file-used-a-nested-function) post, you are using clang rather than gcc.

**Comment by bolton-lab** [comment]
Thanks Giulio, looks like anaconda3 used clang and it was first in my path so that fixed it.
