### ISSUE TITLE
Why HMM?

### ISSUE THREAD

**Issue by victormaricato** [freeseek/mocha#15]
Hi, I read both papers referenced in README.md in the default branch however I could not find the justification for choosing Hidden Markov Model (HMM) for this modeling. Although you provide proof of its performance and its downsides (alongside what you did to correct for these issues), would be great to know why HMM.

Is there any reason or was it just due to previous publication (such as these:

> There are a few differences between MoChA and the HMM model used in Loh et al. 2018, Thompson et al. 2019, Loh et al. 2020, and Terao et al. 2020.

)

(This is not a critic, just curiosity)

**Comment by freeseek** [comment]
A lot of algorithms that work with variation along the chromosomes use HMMs. The main reason is not that the processes generating the events are Markov (they are not), but it is simply related to the ability of dynamic algorithms to explore the exponential space of all possible mosaic chromosomal alterations events on a chromosome in a way that is linear in complexity on the number of SNPs in a chromosome. So the best answer for why we use HMMs is to make the detection algorithm fast. You could argue that it is even too fast (MoChA takes ~1s to run the full genome for array data), so it would be okay to run some alternative algorithms. Personally having a fast runtime helped me as a developer with testing different models without having to wait. The way you set transition probabilities in the HMM is driven by the priors you associate to a given chromosomal event, with some constraints due to the nature of the HMM algorithms. MoChA uses a fair amount of tricks to change the priors for events that reach all the way to the telomeres and events that cross the centromeres. It is not a fully principled approach, but it works well.

**Comment by victormaricato** [comment]
@freeseek Thank you very much for your excellent & clear explanation!
