### ISSUE TITLE
impute5

### ISSUE THREAD

**Issue by yifnzhao** [freeseek/mocha#18]
Hi,

I understand this might not be the best place to ask about impute5, but I am wondering if you have any clue how the error below could be resolved?

I was trying to run the imputation part of the pipeline, i.e.,
```
for chr in {1..22} X; do
  zcat $map | sed 's/^23/X/' | awk -v chr=$chr '$1==chr {print chr,".",$4,$2}' > $dir/genetic_map.chr$chr.txt
  impute5 \
    --h $panel_pfx${chr}$panel_sfx.bcf \
    --m $dir/genetic_map.chr$chr.txt \
    --g $dir/$pfx.pgt.bcf \
    --r chr$chr \
    --o $dir/$pfx.chr$chr.imp.bcf \
    --l $dir/$pfx.chr$chr.log \
    --threads $thr
done
```
And had the following error for every chromosome:
```
IMPUTE v5
        Simone Rubinacci and Jonathan Marchini, 2020

Version: 1.1.4
Started: 04/01/2022 - 16:00:23
________________________________

Options:
--b 250
--g 5219.pgt.bcf
--h ALL.chr6.phase3_integrated.20130502.genotypes.bcf
--l 5219.chr6.log
--m genetic_map.chr6.txt
--ne 20000
--o 5219.chr6.imp.bcf
--pbwt-cm 0.02
--pbwt-depth 4
--r chr6
--threads 4

ERROR: No in common between reference and target panels.
```

Yifan

**Comment by freeseek** [comment]
I think this means the `ALL.chr6.phase3_integrated.20130502.genotypes.bcf` and the `5219.chr6.imp.bcf` VCFs have no variants in common on `chr6`. What I notice is that `ALL.chr6.phase3_integrated.20130502.genotypes.bcf` is the VCF with GRCh37 variants, so the region used would have to be `6` rather than `chr6`. My advice is to avoid GRCh37 and use the `CCDG_14151_B01_GRM_WGS_2020-08-05_chr6.filtered.phased.bcf` GRCh38 VCF instead, making sure your data matches the same reference. Also, the latest version of IMPUTE5 is currently 1.1.5

**Comment by yifnzhao** [comment]
Yes indeed. It works now with region flag changed to `6` from `chr6`. Thank you!
