### ISSUE TITLE
Conceptual Confusion about CNV and mCA

### ISSUE THREAD

**Issue by Xxhongs** [freeseek/mocha#30]
Hi Giulio,

we know mocha can call mosaic chromosomal alterations from array data with BAF and LRR information, and pennCNV is a useful tool to call CNV from array data with BAF and LRR information, too.  The frameworks of mocha and penncnv are based on HMM.

So I'm a little confused about the concept of CNV and mCA. 

Can you simply help me distinguish the two and tell me the difference between penncnv and mocha in methods.

Thanks.

**Comment by freeseek** [comment]
PennCNV uses a HMM to identify germline/consitutional CNVs from BAF and LRR. PennCNV only allows integer copy number states as hidden states in the Markov model. Conversely, MoChA uses a HMM to identify both germline/constitutional CNVs and somatic/mosaic mCAs from BAF augmented with phase and LRR and it uses an array of hidden states to model events at different cell fractions. PennCNV will occasionally identify somatic/mosaic mCAs but it is not designed to do so and since it does not use phase information it is not powered to find somatic/mosaic mCAs at low cell fractions for which phase information is key to infer the presence of an event. Excluding hapLOH, MoChA is currently the the only software that levarages population based phasing to detect mCAs. However, hapLOH uses a simpler model that is not as powered as the model used by MoChA.

**Comment by Xxhongs** [comment]
A very detailed explanation also solved my doubts.
Thanks again.
